# Generated by Django 4.2.1 on 2023-05-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Self_Contain', 'Self_Contain'), ('Two_Bed', 'Two_Bed'), ('Three_Bed', 'Three_Bed'), ('Four_Bed', 'Four_Bed'), ('Five_Bed', 'Five_Bed')], default=('Self_Contain', 'Self_Contain'), max_length=12)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('profile_image', models.ImageField(upload_to='images/profile/%Y%M%D')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('profile_image', models.ImageField(upload_to='images/profile/%Y%M%D')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/land/%Y%M%D')),
                ('lands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.lands')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/apartment/%Y%M%D')),
                ('apartments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.apartments')),
            ],
        ),
    ]
